version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    # image: wouerner/iqoption-nginx-backend
    container_name: iqoption-nginx-backend
    # user: $USER
    working_dir: /app
    volumes:
      - .:/var/www/html
      - .:/app
        # - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:8081"
      - "8443:8443"
    depends_on:
      - "mongo"
      - "php-fpm"

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    #image: wouerner/iqoption-php-fpm
    container_name: iqoption-php-fpm-backend
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    depends_on:
      - "mongo"

  mongo:
    container_name: iqoption-mongodb
    image: wouerner/iqoption-mongodb
    # build:
    #   context: .
    #   dockerfile: docker/mongo/Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_DATA_DIR: /data
    volumes:
      - ./data:/data
      - ./backup:/backup
    ports:
      - "27017:27017"


#    networks:
#      static-network:
#        ipv4_address: 172.20.0.3
# networks:
#   static-network:
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16
#          iprange: 172.28.5.0/24
