apiVersion: apps/v1
kind: Deployment
metadata:
  name: iqoption-nginx-backend-php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iqoption
      tier: php
  template:
    metadata:
      labels:
        app: iqoption
        tier: php
    spec:
      containers:
        - name: iqoption-nginx-backend
          image: wouerner/iqoption-php-fpm:latest
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
          env:
          - name: APP_DEBUG
            value: "true"
          - name: DB_HOST
            value: "mongo"
          - name: DB_PORT
            value: "27017"
          - name: DB_DATABASE
            value: "iqoption"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            value: "root"
          - name: JWT_SECRET
            value: "SlnG0QnLzt8OSXYnEHLwMQ0NWa2TEgYnB06ojwVllENeWQJ7t1fFUxmb0dXlb8xn"




