apiVersion: apps/v1
kind: Deployment
metadata:
  name: iqoption-nginx-backend-php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iqoption
      tier: php
  template:
    metadata:
      labels:
        app: iqoption
        tier: php
    spec:
      containers:
        - name: iqoption-nginx-backend
          image: wouerner/iqoption-php-fpm:latest
          ports:
            - containerPort: 9000
