apiVersion: v1
kind: Service
metadata:
  name: servico-ioption-nginx
  labels:
    tier: backend
    app: iqoption
spec:
  type: LoadBalancer
  selector:
    app: iqoption
    tier: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
