apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: iqoption
    tier: php
spec:
  # type: LoadBalancer
  selector:
    app: iqoption
    tier: php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

  # externalIPs:
  #   - 192.168.99.100
