apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statefulset-mongo
spec:
  serviceName: mongo
  template:
    metadata:
      labels:
        name: iqoption-mongodb
    spec:
      containers:
        - name: iqoption-mongodb
          image: wouerner/iqoption-mongodb:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
            - name: MONGO_DATA_DIR
              value: /data
          volumeMounts:
            - name: volume-mongodb
              mountPath: /data
      volumes:
        - name: volume-mongodb
          persistentVolumeClaim:
            claimName: configuracao-mongo
